import 'package:saju/saju.dart';
import 'package:test/test.dart';

void main() {
  group('Ten Gods', () {
    test('determines correct ten god for same element same polarity', () {
      // 甲 (Wood Yang) to 甲 (Wood Yang) = 비견
      final result = getTenGodKey(Stem.jia, Stem.jia);
      expect(result, equals(TenGod.companion));
    });

    test('determines correct ten god for same element different polarity', () {
      // 甲 (Wood Yang) to 乙 (Wood Yin) = 겁재
      final result = getTenGodKey(Stem.jia, Stem.yi);
      expect(result, equals(TenGod.robWealth));
    });

    test('determines correct ten god for generating element same polarity', () {
      // 甲 (Wood) generates 丙 (Fire) same polarity = 식신
      final result = getTenGodKey(Stem.jia, Stem.bing);
      expect(result, equals(TenGod.eatingGod));
    });

    test('determines correct ten god for generating element different polarity', () {
      // 甲 (Wood) generates 丁 (Fire) different polarity = 상관
      final result = getTenGodKey(Stem.jia, Stem.ding);
      expect(result, equals(TenGod.hurtingOfficer));
    });

    test('determines correct ten god for controlling element same polarity', () {
      // 甲 (Wood) controls 戊 (Earth) same polarity = 편재
      final result = getTenGodKey(Stem.jia, Stem.wu);
      expect(result, equals(TenGod.indirectWealth));
    });

    test('determines correct ten god for controlling element different polarity', () {
      // 甲 (Wood) controls 己 (Earth) different polarity = 정재
      final result = getTenGodKey(Stem.jia, Stem.ji);
      expect(result, equals(TenGod.directWealth));
    });

    test('determines correct ten god for controlled by same polarity', () {
      // 甲 (Wood) controlled by 庚 (Metal) same polarity = 편관
      final result = getTenGodKey(Stem.jia, Stem.geng);
      expect(result, equals(TenGod.sevenKillings));
    });

    test('determines correct ten god for controlled by different polarity', () {
      // 甲 (Wood) controlled by 辛 (Metal) different polarity = 정관
      final result = getTenGodKey(Stem.jia, Stem.xin);
      expect(result, equals(TenGod.directOfficer));
    });

    test('determines correct ten god for generated by same polarity', () {
      // 甲 (Wood) generated by 壬 (Water) same polarity = 편인
      final result = getTenGodKey(Stem.jia, Stem.ren);
      expect(result, equals(TenGod.indirectSeal));
    });

    test('determines correct ten god for generated by different polarity', () {
      // 甲 (Wood) generated by 癸 (Water) different polarity = 정인
      final result = getTenGodKey(Stem.jia, Stem.gui);
      expect(result, equals(TenGod.directSeal));
    });
  });

  group('Hidden Stems', () {
    test('returns correct hidden stems for 子', () {
      final stems = HiddenStems.forBranch(Branch.zi);
      expect(stems.length, equals(1));
      expect(stems[0].stem, equals(Stem.gui));
      expect(stems[0].weight, equals(1.0));
    });

    test('returns correct hidden stems for 丑', () {
      final stems = HiddenStems.forBranch(Branch.chou);
      expect(stems.length, equals(3));
      expect(stems[0].stem, equals(Stem.ji));
      expect(stems[1].stem, equals(Stem.gui));
      expect(stems[2].stem, equals(Stem.xin));
    });

    test('primary stem is first in list', () {
      final primary = HiddenStems.primaryStem(Branch.yin);
      expect(primary, equals(Stem.jia));
    });
  });
}
