import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerTools as registerAppTools } from "@/tools/app.js";
import { registerTools as registerAppstoreOrderTools } from "@/tools/appstore-order.js";
import { registerTools as registerAppstorePaymentTools } from "@/tools/appstore-payment.js";
import { registerArticleIconTools } from "@/tools/article-icon.js";
import { registerTools as registerAutomessageTools } from "@/tools/automessage.js";
import { registerTools as registerBenefitTools } from "@/tools/benefit.js";
import { registerTools as registerBoardTools } from "@/tools/board.js";
import { registerTools as registerBrandTools } from "@/tools/brand.js";
import { registerTools as registerBundleProductTools } from "@/tools/bundleproduct.js";
import { registerTools as registerCancellationTools } from "@/tools/cancellation.js";
import { registerTools as registerCartTools } from "@/tools/cart.js";
import { registerTools as registerCashReceiptTools } from "@/tools/cashreceipt.js";
import { registerTools as registerCategoryDecorationImagesTools } from "@/tools/category-decoration-images.js";
import { registerTools as registerCategorySeoTools } from "@/tools/category-seo.js";
import { registerTools as registerCategoryProductTools } from "@/tools/categoryproduct.js";
import { registerTools as registerCategoryPropertyTools } from "@/tools/categoryproperty.js";
import { registerTools as registerClassificationTools } from "@/tools/classification.js";
import { registerTools as registerCollectRequestTools } from "@/tools/collect-request.js";
import { registerTools as registerCommonEventTools } from "@/tools/common-event.js";
import { registerTools as registerCouponTools } from "@/tools/coupon.js";
import { registerTools as registerCouponIssuanceCustomersTools } from "@/tools/coupon-issuance-customers.js";
import { registerTools as registerCouponIssuesTools } from "@/tools/coupon-issues.js";
import { registerTools as registerCurrencyTools } from "@/tools/currency.js";
import { registerTools as registerCustomerTools } from "@/tools/customer.js";
import { registerTools as registerCustomerCouponTools } from "@/tools/customer-coupons.js";
import { registerTools as registerCustomerEventTools } from "@/tools/customer-events.js";
import { registerCustomerGroupTools } from "@/tools/customer-group.js";
import { registerCustomerMemoTools } from "@/tools/customer-memo.js";
import { registerTools as registerCustomerPaymentInfoTools } from "@/tools/customer-payment-info.js";
import { registerTools as registerCustomerPlusAppTools } from "@/tools/customer-plus-app.js";
import { registerTools as registerCustomerPropertyTools } from "@/tools/customer-property.js";
import { registerTools as registerDashboardTools } from "@/tools/dashboard.js";
import { registerTools as registerDatabridgeLogsTools } from "@/tools/databridge-logs.js";
import { registerTools as registerDiscountCodeTools } from "@/tools/discount-codes.js";
import { registerTools as registerDormantTools } from "@/tools/dormant.js";
import { registerTools as registerExchangeTools } from "@/tools/exchange.js";
import { registerTools as registerExchangeRequestTools } from "@/tools/exchange-request.js";
import { registerTools as registerFulfillmentTools } from "@/tools/fulfillment.js";
import { registerTools as registerImageTools } from "@/tools/image.js";
import { registerTools as registerInformationTools } from "@/tools/information.js";
import { registerTools as registerKakaoTools } from "@/tools/kakao.js";
import { registerTools as registerLabelTools } from "@/tools/label.js";
import { registerTools as registerMainTools } from "@/tools/main.js";
import { registerTools as registerMainProductsTools } from "@/tools/mainproducts.js";
import { registerTools as registerManufacturerTools } from "@/tools/manufacturer.js";
import { registerTools as registerMenuTools } from "@/tools/menu.js";
import { registerTools as registerMobileTools } from "@/tools/mobile.js";
import { registerTools as registerOrderTools } from "@/tools/order.js";
import { registerTools as registerOrderBenefitTools } from "@/tools/order-benefit.js";
import { registerBuyerTools as registerOrderBuyerTools } from "@/tools/order-buyer.js";
import { registerTools as registerOrderControlTools } from "@/tools/order-control.js";
import { registerTools as registerOrderDashboardTools } from "@/tools/order-dashboard.js";
import { registerTools as registerOrderItemTools } from "@/tools/order-item.js";
import { registerTools as registerOrderItemLabelTools } from "@/tools/order-item-label.js";
import { registerTools as registerOrderItemOptionTools } from "@/tools/order-item-option.js";
import { registerTools as registerOrderMemoTools } from "@/tools/order-memo.js";
import { registerTools as registerOrderPaymentTools } from "@/tools/order-payment.js";
import { registerTools as registerOrderPaymentAmountTools } from "@/tools/order-payment-amount.js";
import { registerTools as registerOrderReceiverTools } from "@/tools/order-receiver.js";
import { registerTools as registerOrderFormTools } from "@/tools/orderform.js";
import { registerTools as registerOrderformPropertiesTools } from "@/tools/orderform-properties.js";
import { registerTools as registerOrderSettingTools } from "@/tools/ordersetting.js";
import { registerTools as registerOriginTools } from "@/tools/origin.js";
import { registerTools as registerPaymentTools } from "@/tools/payment.js";
import { registerTools as registerPointsTools } from "@/tools/points.js";
import { registerTools as registerPolicyTools } from "@/tools/policy.js";
import { registerTools as registerPrivacyTools } from "@/tools/privacy.js";
import { registerTools as registerProductAdminTools } from "@/tools/product-admin.js";
import { registerTools as registerProductAssetsTools } from "@/tools/product-assets.js";
import { registerTools as registerProductBasicsTools } from "@/tools/product-basics.js";
import { registerTools as registerProductCategoryTools } from "@/tools/product-category.js";
import { registerTools as registerProductCustomPropertiesTools } from "@/tools/product-customproperties.js";
import { registerTools as registerProductDisplayTools } from "@/tools/product-display.js";
import { registerTools as registerProductImagesTools } from "@/tools/product-images.js";
import { registerTools as registerProductInventoriesTools } from "@/tools/product-inventories.js";
import { registerTools as registerProductIconsTools } from "@/tools/product-marketing.js";
import { registerTools as registerProductMemosTools } from "@/tools/product-memos.js";
import { registerTools as registerProductOptionsTools } from "@/tools/product-options.js";
import { registerTools as registerProductPropertiesTools } from "@/tools/product-properties.js";
import { registerTools as registerProductSeoTools } from "@/tools/product-seo.js";
import { registerTools as registerProductSettingTools } from "@/tools/product-setting.js";
import { registerTools as registerProductTagsTools } from "@/tools/product-tags.js";
import { registerTools as registerProductVariantsTools } from "@/tools/product-variants.js";
import { registerTools as registerPromotionTools } from "@/tools/promotion.js";
import { registerTools as registerRecipeTools } from "@/tools/recipe.js";
import { registerTools as registerRedirectTools } from "@/tools/redirect.js";
import { registerTools as registerRefundTools } from "@/tools/refund.js";
import { registerTools as registerRestockTools } from "@/tools/restock.js";
import { registerTools as registerReturnTools } from "@/tools/return.js";
import { registerTools as registerReturnRequestTools } from "@/tools/return-request.js";
import { registerTools as registerSalesTools } from "@/tools/sales.js";
import { registerTools as registerScripttagsTools } from "@/tools/scripttags.js";
import { registerTools as registerSeoTools } from "@/tools/seo.js";
import { registerTools as registerSerialCouponIssueTools } from "@/tools/serialcoupon-issue.js";
import { registerTools as registerSerialCouponTools } from "@/tools/serialcoupons.js";
import { registerTools as registerShipmentTools } from "@/tools/shipment.js";
import { registerTools as registerShippingFeeCancellationTools } from "@/tools/shipping-fee-cancellation.js";
import { registerTools as registerShippingSupplierTools } from "@/tools/shipping-supplier.js";
import { registerTools as registerShippingManagerTools } from "@/tools/shippingmanager.js";
import { registerTools as registerShopTools } from "@/tools/shop.js";
import { registerTools as registerSmsTools } from "@/tools/sms.js";
import { registerTools as registerSocialAppleTools } from "@/tools/socialapple.js";
import { registerTools as registerSocialNaverShoppingTools } from "@/tools/socialnavershopping.js";
import { registerTools as registerStoreTools } from "@/tools/store.js";
import { registerTools as registerSubscriptionTools } from "@/tools/subscription.js";
import { registerTools as registerSupplierTools } from "@/tools/supplier.js";
import { registerTools as registerTaxManagerTools } from "@/tools/taxmanager.js";
import { registerTools as registerThemeTools } from "@/tools/theme.js";
import { registerTools as registerTrendTools } from "@/tools/trend.js";
import { registerUrgentInquiryTools } from "@/tools/urgent-inquiry.js";
import { registerTools as registerWebhookLogsTools } from "@/tools/webhook-logs.js";
import { registerTools as registerWebhookSettingTools } from "@/tools/webhook-setting.js";

/**
 * Register all Cafe24 Admin tools with the MCP server
 */
export function registerAllTools(server: McpServer): void {
  registerAppTools(server);
  registerAppstoreOrderTools(server);
  registerAppstorePaymentTools(server);
  registerAutomessageTools(server);
  registerBenefitTools(server);
  registerBoardTools(server);
  registerBrandTools(server);
  registerCancellationTools(server);
  registerCartTools(server);
  registerCashReceiptTools(server);
  registerCategoryDecorationImagesTools(server);
  registerCategoryProductTools(server);
  registerCategoryPropertyTools(server);
  registerCategorySeoTools(server);
  registerClassificationTools(server);
  registerCollectRequestTools(server);
  registerCommonEventTools(server);
  registerOrderControlTools(server);
  registerOrderDashboardTools(server);
  registerExchangeTools(server);
  registerExchangeRequestTools(server);
  registerFulfillmentTools(server);
  registerCouponTools(server);
  registerCouponIssuanceCustomersTools(server);
  registerCouponIssuesTools(server);
  registerSerialCouponIssueTools(server);
  registerCurrencyTools(server);
  registerCustomerTools(server);
  registerCustomerCouponTools(server);
  registerCustomerEventTools(server);
  registerCustomerGroupTools(server);
  registerCustomerMemoTools(server);
  registerCustomerPaymentInfoTools(server);
  registerCustomerPlusAppTools(server);
  registerCustomerPropertyTools(server);
  registerDatabridgeLogsTools(server);
  registerDashboardTools(server);
  registerDiscountCodeTools(server);
  registerDormantTools(server);
  registerImageTools(server);
  registerInformationTools(server);
  registerKakaoTools(server);
  registerLabelTools(server);
  registerMainTools(server);
  registerMainProductsTools(server);
  registerManufacturerTools(server);
  registerMenuTools(server);
  registerMobileTools(server);
  registerOrderTools(server);
  registerOrderBenefitTools(server);
  registerOrderItemTools(server);
  registerOrderBuyerTools(server);
  registerOrderItemLabelTools(server);
  registerOrderItemOptionTools(server);
  registerOrderMemoTools(server);
  registerOrderformPropertiesTools(server);
  registerOrderFormTools(server);
  registerOrderSettingTools(server);
  registerOrderPaymentTools(server);
  registerOrderPaymentAmountTools(server);
  registerOrderReceiverTools(server);
  registerOriginTools(server);
  registerPaymentTools(server);
  registerPointsTools(server);
  registerPolicyTools(server);
  registerPrivacyTools(server);
  registerProductBasicsTools(server);
  registerProductImagesTools(server);
  registerProductAdminTools(server);
  registerProductAssetsTools(server);
  registerProductCategoryTools(server);
  registerProductCustomPropertiesTools(server);
  registerProductIconsTools(server);
  registerProductDisplayTools(server);
  registerProductPropertiesTools(server);
  registerProductSettingTools(server);
  registerProductMemosTools(server);
  registerProductOptionsTools(server);
  registerProductSeoTools(server);
  registerProductTagsTools(server);
  registerProductVariantsTools(server);
  registerProductInventoriesTools(server);
  registerPromotionTools(server);
  registerRedirectTools(server);
  registerRefundTools(server);
  registerRecipeTools(server);
  registerReturnTools(server);
  registerReturnRequestTools(server);
  registerRestockTools(server);
  registerSalesTools(server);
  registerSeoTools(server);
  registerScripttagsTools(server);
  registerSerialCouponTools(server);
  registerShipmentTools(server);
  registerShippingFeeCancellationTools(server);
  registerShippingManagerTools(server);
  registerShippingSupplierTools(server);
  registerShopTools(server);
  registerSmsTools(server);
  registerSocialAppleTools(server);
  registerSocialNaverShoppingTools(server);
  registerStoreTools(server);
  registerSubscriptionTools(server);
  registerSupplierTools(server);
  registerTaxManagerTools(server);
  registerThemeTools(server);
  registerTrendTools(server);
  registerBundleProductTools(server);
  registerArticleIconTools(server);
  registerUrgentInquiryTools(server);
  registerWebhookLogsTools(server);
  registerWebhookSettingTools(server);
}
