import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerTools as registerAppTools } from "./app.js";
import { registerTools as registerAutomessageTools } from "./automessage.js";
import { registerTools as registerBenefitTools } from "./benefit.js";
import { registerTools as registerBoardTools } from "./board.js";
import { registerTools as registerBundleProductTools } from "./bundleproduct.js";
import { registerTools as registerCartTools } from "./cart.js";
import { registerTools as registerCouponTools } from "./coupon.js";
import { registerTools as registerCurrencyTools } from "./currency.js";
import { registerTools as registerCustomerTools } from "./customer.js";
import { registerTools as registerDashboardTools } from "./dashboard.js";
import { registerTools as registerDormantTools } from "./dormant.js";
import { registerTools as registerImageTools } from "./image.js";
import { registerTools as registerInformationTools } from "./information.js";
import { registerTools as registerKakaoTools } from "./kakao.js";
import { registerTools as registerMainTools } from "./main.js";
import { registerTools as registerMenuTools } from "./menu.js";
import { registerTools as registerMiscTools } from "./misc.js";
import { registerTools as registerMobileTools } from "./mobile.js";
import { registerTools as registerOrderTools } from "./order.js";
import { registerTools as registerOrderFormTools } from "./orderform.js";
import { registerTools as registerOrderSettingTools } from "./ordersetting.js";
import { registerTools as registerPaymentTools } from "./payment.js";
import { registerTools as registerPointsTools } from "./points.js";
import { registerTools as registerPolicyTools } from "./policy.js";
import { registerTools as registerPrivacyTools } from "./privacy.js";
import { registerTools as registerProductTools } from "./product.js";
import { registerTools as registerProductDisplayTools } from "./productdisplay.js";
import { registerTools as registerProductPropertiesTools } from "./productproperties.js";
import { registerTools as registerProductSettingTools } from "./productsetting.js";
import { registerTools as registerPromotionTools } from "./promotion.js";
import { registerTools as registerRedirectTools } from "./redirect.js";
import { registerTools as registerRestockTools } from "./restock.js";
import { registerTools as registerSeoTools } from "./seo.js";
import { registerTools as registerShippingManagerTools } from "./shippingmanager.js";
import { registerTools as registerShopTools } from "./shop.js";
import { registerTools as registerSmsTools } from "./sms.js";
import { registerTools as registerSocialAppleTools } from "./socialapple.js";
import { registerTools as registerSocialNaverShoppingTools } from "./socialnavershopping.js";
import { registerTools as registerStoreTools } from "./store.js";
import { registerTools as registerSubscriptionTools } from "./subscription.js";
import { registerTools as registerTaxManagerTools } from "./taxmanager.js";

/**
 * Register all Cafe24 Admin tools with the MCP server
 */
export function registerAllTools(server: McpServer): void {
  registerAppTools(server);
  registerAutomessageTools(server);
  registerBenefitTools(server);
  registerBoardTools(server);
  registerCartTools(server);
  registerCouponTools(server);
  registerCurrencyTools(server);
  registerCustomerTools(server);
  registerDashboardTools(server);
  registerDormantTools(server);
  registerImageTools(server);
  registerInformationTools(server);
  registerKakaoTools(server);
  registerMainTools(server);
  registerMenuTools(server);
  registerMobileTools(server);
  registerMiscTools(server);
  registerOrderTools(server);
  registerOrderFormTools(server);
  registerOrderSettingTools(server);
  registerPaymentTools(server);
  registerPointsTools(server);
  registerPolicyTools(server);
  registerPrivacyTools(server);
  registerProductTools(server);
  registerProductDisplayTools(server);
  registerProductPropertiesTools(server);
  registerProductSettingTools(server);
  registerPromotionTools(server);
  registerRedirectTools(server);
  registerRestockTools(server);
  registerSeoTools(server);
  registerShippingManagerTools(server);
  registerShopTools(server);
  registerSmsTools(server);
  registerSocialAppleTools(server);
  registerSocialNaverShoppingTools(server);
  registerStoreTools(server);
  registerSubscriptionTools(server);
  registerTaxManagerTools(server);
  registerBundleProductTools(server);
}
